# Site settings
title: ODK XForms Specification
email: 
description: "Documents the XForms and OpenRosa-derived form specification as supported by ODK-compliant tools."
baseurl: "/xforms-spec"
url: ""

# Build settings
markdown: kramdown
safe: true
highlighter: rouge
collections:
- sections

plugins:
  - jekyll-redirect-from